version: '3.4'

services:
  node:
    build: .
    ports:
      - 3000:3000
      - 5000:5000
    command: ["npm", "run", "dev"]
    volumes: 
      - .:/usr/src/app
    links: 
      - mongodb
  
  mongodb:
    image: mongo:4.0.0
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db

volumes: 
  data: 